use modern constructor for auth_plugin_loginlogoutredir
hrimhari/moodle-auth_loginlogoutredir pull request #6
Opened 2020-08-24 12:50 UTC by grillonbleu

Resolves the following deprecation message:

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; auth_plugin_loginlogoutredir has a deprecated constructor

2020-08-24 14:55 UTC, hrimhari commented
Looks good to me. Could you also bump the 2 last digits on the build version and the last digit of the plugin version pweez?

2020-08-24 19:59 UTC, grillonbleu commented
Sure! Is it OK like this?

2020-08-24 20:15 UTC, hrimhari requested changes
Oh sorry, I didn't realize this was for loginlogout! Actually version would be bumped to today and release would be set to  1.0.1. Thank you!

2020-08-25 13:19 UTC, grillonbleu commented
Changed accordingly!

2020-08-25 15:47 UTC, hrimhari approved these changes

2020-08-25 15:52 UTC, merged

2020-08-26 01:16 UTC, hrimhari commented
What Moodle version are you using this plugin for?

2020-08-26 17:58 UTC, grillonbleu commented
I've used this plugin on a few Moodle versions already. The most up to date Moodle I've installed it on is 3.7 (PHP 7.1).

2020-08-26 18:00 UTC, grillonbleu commented
I might install it soon on 3.9 (PHP 7.3) though.